import time
import os
import smtplib
import RPi.GPIO as GPIO
from hx711 import HX711
from picamera2 import Picamera2
from datetime import datetime

from email.message import EmailMessage

# ---------------- GPIO PINS ----------------
IR_PIN = 17          # IR sensor output pin
BUZZER_PIN = 27      # Buzzer signal pin
HX_DT = 5            # HX711 DT
HX_SCK = 6           # HX711 SCK

# ---------------- SETTINGS ----------------
ALARM_DURATION = 5
WEIGHT_THRESHOLD = 100
IMAGE_FOLDER = "captures"

# ---------------- EMAIL SETTINGS ----------------
SENDER_EMAIL = "rv35751@gmail.com"         # CHANGE THIS
SENDER_PASSWORD = "raj@12345"        # CHANGE THIS
RECEIVER_EMAIL = "rv35751@gmail.com" # CHANGE THIS

# ---------------- GPIO SETUP ----------------
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

GPIO.setup(IR_PIN, GPIO.IN)
GPIO.setup(BUZZER_PIN, GPIO.OUT)

# Active LOW buzzer
GPIO.output(BUZZER_PIN, GPIO.HIGH)   # buzzer OFF at startup

# ---------------- BUZZER FUNCTIONS ----------------
def buzzer_on():
    GPIO.output(BUZZER_PIN, GPIO.LOW)

def buzzer_off():
    GPIO.output(BUZZER_PIN, GPIO.HIGH)

# ---------------- CAMERA SETUP ----------------
camera = Picamera2()
camera.configure(camera.create_still_configuration())
camera.start()
time.sleep(2)

# ---------------- HX711 SETUP ----------------
hx = HX711(HX_DT, HX_SCK)

REFERENCE_UNIT = 200

hx.set_reading_format("MSB", "MSB")
hx.set_reference_unit(REFERENCE_UNIT)
hx.reset()
hx.tare()

print("Load cell tared successfully.")
print("Keep the platform empty while starting...")
time.sleep(2)

# ---------------- FOLDER SETUP ----------------
os.makedirs(IMAGE_FOLDER, exist_ok=True)

# ---------------- HELPER FUNCTIONS ----------------
def get_weight():
    try:
        weight = hx.get_weight(5)
        hx.power_down()
        hx.power_up()
        return round(weight, 2)
    except Exception as e:
        print("Weight read error:", e)
        return 0

def capture_image(reason):
    try:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{IMAGE_FOLDER}/{reason}_{timestamp}.jpg"
        camera.capture_file(filename)
        print(f"[CAMERA] Image saved: {filename}")
        return filename
    except Exception as e:
        print("Camera capture error:", e)
        return None

def send_email_alert(reason, image_path=None):
    try:
        msg = EmailMessage()
        msg["Subject"] = f"Anti-Theft Alert: {reason}"
        msg["From"] = SENDER_EMAIL
        msg["To"] = RECEIVER_EMAIL

        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        msg.set_content(f"""
Alert Detected!

Reason: {reason}
Time: {current_time}

This alert was generated by your Raspberry Pi Anti-Theft Flooring System.
""")

        # Attach image if available
        if image_path and os.path.exists(image_path):
            with open(image_path, "rb") as img_file:
                img_data = img_file.read()
                img_name = os.path.basename(image_path)
                msg.add_attachment(img_data, maintype="image", subtype="jpeg", filename=img_name)

        # Send email
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(SENDER_EMAIL, SENDER_PASSWORD)
            smtp.send_message(msg)

        print("[EMAIL] Alert email sent successfully.")

    except Exception as e:
        print("Email sending error:", e)

def trigger_alarm(reason):
    print(f"[ALERT] {reason}")

    image_path = capture_image(reason)

    print(f"[BUZZER] ON for {ALARM_DURATION} seconds...")
    buzzer_on()
    time.sleep(ALARM_DURATION)
    buzzer_off()
    print("[BUZZER] OFF")

    send_email_alert(reason, image_path)

# ---------------- DETECTION LOCKS ----------------
weight_triggered = False
ir_triggered = False

# ---------------- MAIN LOOP ----------------
print("====================================")
print("ANTI-THEFT FLOOR SYSTEM STARTED")
print("Monitoring weight and IR sensor...")
print("====================================")

try:
    while True:
        ir_state = GPIO.input(IR_PIN)
        current_weight = get_weight()

        print(f"IR = {ir_state}, Weight = {current_weight}")

        # ==========================================
        # WEIGHT DETECTION
        # ==========================================
        if current_weight > WEIGHT_THRESHOLD and not weight_triggered:
            trigger_alarm("Weight_Exceeded")
            weight_triggered = True
            print("[LOCK] Weight alarm locked until weight becomes normal.")

        elif current_weight <= WEIGHT_THRESHOLD and weight_triggered:
            print("[RESET] Weight back to normal. System re-armed.")
            weight_triggered = False

        # ==========================================
        # IR DETECTION
        # ==========================================
        if ir_state == 0 and not ir_triggered:
            trigger_alarm("IR_Detected")
            ir_triggered = True
            print("[LOCK] IR alarm locked until object moves away.")

        elif ir_state == 1 and ir_triggered:
            print("[RESET] IR back to normal.")
            ir_triggered = False

        time.sleep(0.5)

except KeyboardInterrupt:
    print("Program stopped by user.")

finally:
    buzzer_off()
    GPIO.cleanup()
